name: audit

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  # cancel-in-progress: true

# permissions: write-all

jobs:
  audit:
    name: Audit
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Homebrew env
        uses: ./.github/actions/homebrew-env

      - name: Brew Tap
        uses: ./.github/actions/brew-tap

      - name: Brew Audit
        shell: bash -ieo pipefail {0}
        env:
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          rsync -lrv --exclude=.git "$(pwd)" "$(brew --repository brewforge/chinese)"
          cd "$(brew --repository brewforge/chinese)"
          ./.github/actions/brew-audit/script.sh
